
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'nyc_taxi_pipeline'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'nyc_taxi_pipeline'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
models:
  # Cấu hình chung cho toàn bộ project
  # Mặc định, tất cả model sẽ được lưu dưới dạng "view"
  +materialized: view

  # Tên project của bạn
  nyc_taxi_pipeline:
    
    # 1. Thư mục "models/staging"
    staging:
      +materialized: view # Staging model nên là view cho nhanh
      # schema (dataset) sẽ lưu các model này
      +schema: staging_layer 
    
    # 2. Thư mục "models/marts"
    marts:
      # 2a. Thư mục "models/marts/dimensions"
      dimensions:
        +materialized: table # Dims nhỏ, nên là table (cost ~$0.00)
        +schema: dimensions # Lưu vào dataset "dimensions"
      
      # 2b. Thư mục "models/marts/facts"
      facts:
        +materialized: view # Facts lớn, giữ view để tiết kiệm
        +schema: facts # Lưu vào dataset "facts"
